SELECT *
 FROM 
 CSCHD_CONTRACT_HEADERS  
	 WHERE
	 region= 1010003098000000
	 AND CSCHD_PK IN (SELECT CONTRACT_CSCHD_FK FROM CSCLS_CONTRACT_LOCATIONS WHERE city='Magellan')
	 AND CSCHD_PK IN (SELECT CONTRACT_CSCHD_FK FROM CSCBS_CONTRACT_BENCHS WHERE bench=1010003073000004 )
	 AND CSCHD_PK IN (SELECT CONTRACT_CSCHD_FK FROM CSCSG_CONTRACT_STORAGES WHERE GRADE_GROUP='MTBE')
	 
	 
