DROP TABLE TROUBLETICKET IF EXISTS;
DROP TABLE NOTE IF EXISTS;
DROP TABLE RELATEDPARTY IF EXISTS;
DROP TABLE RELATEDOBJECT IF EXISTS;


CREATE TABLE TROUBLETICKET 
   (	
    id INTEGER IDENTITY NOT NULL, 
	correlationId VARCHAR(100) NULL, 
	description VARCHAR(1000) NOT NULL, 
	severity VARCHAR(100)NOT NULL, 
	type VARCHAR(200) NOT NULL,
	creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP(), 
	targetResolutionDate TIMESTAMP NULL, 
	status VARCHAR(100) DEFAULT 'Created', 
	subStatus VARCHAR(100) NULL, 
	statusChangeReason VARCHAR(1000) NULL, 
	statusChangeDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP(), 
	resolutionDate TIMESTAMP NULL
	 );
 
CREATE TABLE NOTE
	(
	 noteId INTEGER IDENTITY NOT NULL,
	 ticketId INTEGER NOT NULL,
	 date TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	 author VARCHAR(100) NOT NULL,
	 text VARCHAR(1000) NOT NULL
	);
	
CREATE TABLE RELATEDPARTY
	(
	 partyId INTEGER IDENTITY NOT NULL,
	 ticketId INTEGER NOT NULL,
	 reference VARCHAR(200) NOT NULL,
	 role VARCHAR(100) NOT NULL,
	 name VARCHAR(100),
	 validFor TIMESTAMP
	);

CREATE TABLE RELATEDOBJECT
	(
	 objectId INTEGER IDENTITY NOT NULL,
	 ticketId INTEGER NOT NULL,
	 involvement VARCHAR(200) NOT NULL,
	 reference VARCHAR(100) NOT NULL
	);
	
ALTER TABLE NOTE ADD FOREIGN KEY (ticketId) REFERENCES TROUBLETICKET(id);
ALTER TABLE RELATEDPARTY ADD FOREIGN KEY (ticketId) REFERENCES TROUBLETICKET(id);
ALTER TABLE RELATEDOBJECT ADD FOREIGN KEY (ticketId) REFERENCES TROUBLETICKET(id);
