DROP TABLE IF EXISTS TODOS;

CREATE TABLE TODOS (
  ID INTEGER NOT NULL,
  TITLE VARCHAR(50) NOT NULL,
  COMPLETED BOOLEAN NOT NULL,  
  PRIMARY KEY (ID)
) AS SELECT * FROM CSVREAD('${project.basedir}/src/main/resources/db/data.txt');
