DROP TABLE IF EXISTS TODOS;

CREATE TABLE TODOS (
  ID INTEGER IDENTITY NOT NULL,
  TITLE VARCHAR(50) NOT NULL,
  COMPLETED BOOLEAN NOT NULL,  
  PRIMARY KEY (ID)
) AS SELECT * FROM CSVREAD('${project.basedir}/src/main/resources/db/data.txt');

DROP TABLE IF EXISTS MEMCACHEKEYS;

CREATE TABLE MEMCACHEKEYS (
  ID INTEGER IDENTITY NOT NULL,
  CACHEKEY VARCHAR(50) NOT NULL,
  REFRESHTIMEPERIOD INTEGER NOT NULL,
  LASTREFRESHTIME BIGINT NOT NULL,
  PRIMARY KEY (ID)
); 
