select * from 
(SELECT C.CSCHD_PK,C.TERMINAL,C.REGION,C.ASSET_NAME,C.ASSET_OWNER,C.DEAL_NAME,C.DEAL_COUNTER_PARTY,C.BP_CONTRACT_NUM,C.
EXTERNAL_CONTRACT_NUM,C.OTHER_REFERENCE_NUM,C.DESCRIPTION,C.BP_CONTRACTING_ENTITY,C.LEASE_TYPE,C.LEASE_PERCENTAGE,C.
STATUS,C.CONTRACT_SIGN_DATE,C.CONTRACT_START_DATE,C.CONTRACT_END_DATE,C.CONTRACT_RENEWAL_DATE,C.DURATION_MONTHS,C.
EXCESS_THROUGHPUT_RATE,C.EXCESS_THROUGHPUT_RATE_UOM,C.THROUGPUT_PER_YEAR,C.ECONS,C.ECONS_UOM,C.NOTES,C.
CONTRACT_LINK,C.LOCK_NUM,C.IS_DELETED,C.CREATED_BY,C.CREATED_DATE,C.LAST_UPDATED_BY,C.LAST_UPDATED_DATE 
FROM 
CSCHD_CONTRACT_HEADERS C 
	WHERE C.region='?'
	  AND C.terminal='?'	
	  AND C.ASSET_NAME='?'
	  AND C.ASSET_OWNER='?'
	  AND C.DEAL_NAME='?'
	  AND C.DEAL_COUNTER_PARTY='?'
	  AND C.BP_CONTRACT_NUM='?'
	  AND C.BP_CONTRACTING_ENTITY='?'
	  AND C.STATUS='?'	  
) F
join CSCLS_CONTRACT_LOCATIONS L
	ON L.state='?'
	AND L.country='?'
	AND L.city='?'
	AND L.county='?'
	AND F.CSCHD_PK=L.CONTRACT_CSCHD_FK
join CSCBS_CONTRACT_BENCHS B
	ON B.bench='?' 
	AND C.CSCHD_PK=L.CONTRACT_CSCHD_FK
join CSCSG_CONTRACT_STORAGES S
	ON L.GRADE_GROUP='?'
	AND C.CSCHD_PK=L.CONTRACT_CSCHD_FK